Reverting github build workflows to Jenkins pipelines test
Cray-HPE/cray-import-config pull request #24
Opened 2022-09-20 21:22 UTC by jesseviola-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Target branch correct
- [ ] Testing is appropriate and complete, if applicable
- [ ] Is a new version being released? Update https://github.com/Cray-HPE/cray-import-config/wiki/CSM-Compatibility-Matrix
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-09-22 16:18 UTC, rbak-hpe submitted a review, later dismissed

2022-09-23 18:58 UTC, dlaine-hpe requested changes

2022-09-23 18:58 UTC, dlaine-hpe commented on charts/cray-import-config/values.yaml
> +# Full image including repo, e.g. dtr.dev.cray.com/cray/config-image:1.2.3
Removing referenced to dev.cray.com addresses was deliberate as that domain was retired. I am guessing there should not have been any changes in this file.

2022-09-23 18:58 UTC, dlaine-hpe commented on charts/cray-import-config/Chart.yaml
> +
This is an odd set of changes - are you sure this needed to get pulled in?

2022-09-27 21:44 UTC, dlaine-hpe approved these changes

2022-09-29 16:44 UTC, rbak-hpe approved these changes

2022-09-29 16:48 UTC, merged